# Site
title: Jett Jackson's Blog
description: A blog for all the things I want to write blog posts about
url: https://blog.jettjacksonmedia.com/
logo: logo.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/willian-justen-de-vasconcellos-1135218-unsplash.jpg
  post-list: images/willian-justen-de-vasconcellos-1135236-unsplash.jpg
  default-post: images/antoine-boissonot-1136311-unsplash.jpg

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-45323320-8

# Social Links
email:             jett@jettjacksonmedia.com
#google.plus:        username
twitter:            TRJ_tt
#facebook:           username
github:             J-tt
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]

theme: jekyll-theme-cayman